name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  GO_VERSION: "1.22.5"
  TINYGO_VERSION: "0.33.0"
  GOLANGCI_VERSION: "v1.61"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_VERSION }}

  sdk-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: ${{ env.TINYGO_VERSION }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: ${{ env.TINYGO_VERSION }}
      - uses: wasmCloud/common-actions/install-wash@main
      - uses: cargo-bins/cargo-binstall@main
      - name: Tools
        run: cargo binstall -y wasm-tools

      - name: http-server
        working-directory: _examples/http-server
        run: wash build

      # - name: http-client
      #   working-directory: _examples/http-client
      #   run: wash build
